### ISSUE TITLE
Wizard Not Working

### ISSUE THREAD

**Issue by JohnCampionJr** [creativetimofficial/ct-paper-dashboard-pro-angular#1]
Just purchased.  Downloaded, ran npm install, ng serve and if I go to the wizard page, the tabs do not render correctly and console throws the following error.  It works on your demo page so it seems there is a difference somewhere.

`ERROR TypeError: $(...).validate is not a function
Stack trace:
../../../../../src/app/forms/wizard/wizard.component.ts/WizardComponent.prototype.ngOnInit@http://localhost:4200/3.chunk.js:458:26
checkAndUpdateDirectiveInline@http://localhost:4200/vendor.bundle.js:56882:9
checkAndUpdateNodeInline@http://localhost:4200/vendor.bundle.js:58378:17
checkAndUpdateNode@http://localhost:4200/vendor.bundle.js:58317:16
debugCheckAndUpdateNode@http://localhost:4200/vendor.bundle.js:59178:38
debugCheckDirectivesFn@http://localhost:4200/vendor.bundle.js:59119:13
View_WizardComponent_Host_0/<@ng:///Forms/WizardComponent_Host.ngfactory.js:8:5
debugUpdateDirectives@http://localhost:4200/vendor.bundle.js:59104:12
checkAndUpdateView@http://localhost:4200/vendor.bundle.js:58284:5
callViewAction@http://localhost:4200/vendor.bundle.js:58649:21
execEmbeddedViewsAction@http://localhost:4200/vendor.bundle.js:58607:17
checkAndUpdateView@http://localhost:4200/vendor.bundle.js:58285:5
callViewAction@http://localhost:4200/vendor.bundle.js:58649:21
execComponentViewsAction@http://localhost:4200/vendor.bundle.js:58581:13
checkAndUpdateView@http://localhost:4200/vendor.bundle.js:58290:5
callViewAction@http://localhost:4200/vendor.bundle.js:58649:21
execEmbeddedViewsAction@http://localhost:4200/vendor.bundle.js:58607:17
checkAndUpdateView@http://localhost:4200/vendor.bundle.js:58285:5
callViewAction@http://localhost:4200/vendor.bundle.js:58649:21
execComponentViewsAction@http://localhost:4200/vendor.bundle.js:58581:13
checkAndUpdateView@http://localhost:4200/vendor.bundle.js:58290:5
callWithDebugContext@http://localhost:4200/vendor.bundle.js:59504:39
debugCheckAndUpdateView@http://localhost:4200/vendor.bundle.js:59044:12
../../../core/@angular/core.es5.js/</ViewRef_.prototype.detectChanges@http://localhost:4200/vendor.bundle.js:56215:9
../../../core/@angular/core.es5.js/</ApplicationRef_.prototype.tick/<@http://localhost:4200/vendor.bundle.js:50853:58
../../../core/@angular/core.es5.js/</ApplicationRef_.prototype.tick@http://localhost:4200/vendor.bundle.js:50853:13
next/<@http://localhost:4200/vendor.bundle.js:50730:100
../../../../zone.js/dist/zone.js/</</ZoneDelegate.prototype.invoke@http://localhost:4200/polyfills.bundle.js:2800:17
onInvoke@http://localhost:4200/vendor.bundle.js:49936:24
../../../../zone.js/dist/zone.js/</</ZoneDelegate.prototype.invoke@http://localhost:4200/polyfills.bundle.js:2799:17
../../../../zone.js/dist/zone.js/</</Zone.prototype.run@http://localhost:4200/polyfills.bundle.js:2550:24
../../../core/@angular/core.es5.js/</NgZone.prototype.run@http://localhost:4200/vendor.bundle.js:49867:54
next@http://localhost:4200/vendor.bundle.js:50730:70
../../../core/@angular/core.es5.js/</EventEmitter.prototype.subscribe/schedulerFn<@http://localhost:4200/vendor.bundle.js:49681:36
../../../../rxjs/Subscriber.js/SafeSubscriber.prototype.__tryOrUnsub@http://localhost:4200/vendor.bundle.js:4604:13
../../../../rxjs/Subscriber.js/SafeSubscriber.prototype.next@http://localhost:4200/vendor.bundle.js:4551:17
../../../../rxjs/Subscriber.js/Subscriber.prototype._next@http://localhost:4200/vendor.bundle.js:4491:9
../../../../rxjs/Subscriber.js/Subscriber.prototype.next@http://localhost:4200/vendor.bundle.js:4455:13
../../../../rxjs/Subject.js/Subject.prototype.next@http://localhost:4200/vendor.bundle.js:4199:17
../../../core/@angular/core.es5.js/</EventEmitter.prototype.emit@http://localhost:4200/vendor.bundle.js:49667:54
checkStable@http://localhost:4200/vendor.bundle.js:49901:13
onHasTask@http://localhost:4200/vendor.bundle.js:49949:21
../../../../zone.js/dist/zone.js/</</ZoneDelegate.prototype.hasTask@http://localhost:4200/polyfills.bundle.js:2853:21
../../../../zone.js/dist/zone.js/</</ZoneDelegate.prototype._updateTaskCount@http://localhost:4200/polyfills.bundle.js:2873:17
../../../../zone.js/dist/zone.js/</</Zone.prototype._updateTaskCount@http://localhost:4200/polyfills.bundle.js:2697:17
../../../../zone.js/dist/zone.js/</</Zone.prototype.runTask@http://localhost:4200/polyfills.bundle.js:2617:25
drainMicroTaskQueue@http://localhost:4200/polyfills.bundle.js:3004:25
../../../../zone.js/dist/zone.js/</</ZoneTask.invokeTask@http://localhost:4200/polyfills.bundle.js:2911:21
invokeTask@http://localhost:4200/polyfills.bundle.js:3779:9
globalZoneAwareCallback@http://localhost:4200/polyfills.bundle.js:3797:17`

**Comment by chelaruc** [comment]
Hi @JohnCampionJr,

Thank you for using our product. To fix this error please go in `src/app/forms/wizard/wizard.component.ts` and delete the 36-67 lines.
<img width="595" alt="screen shot 2017-08-01 at 10 59 56" src="https://user-images.githubusercontent.com/22840626/28815041-9f82f364-76a8-11e7-8083-c6e80afb0fd4.png">

Tell us if this worked for you!

Best,
Ciprian

**Comment by JalelTounsi** [comment]
Hello,
I just bought the paper dashboard pro and I, too, got the wizard form not working.
by commenting the lines 36 to 67, I had to comment the line number 78 also because if we don't comment it, the system does not recognize the variable $validator (the one we commented in line 36)

by commenting the two section, I do get a valid display of the wizard but the whole validation process and moving from tab to tab is broken.

**Comment by chelaruc** [comment]
Hi @JalelTounsi 

Thank you for using our product! For fixing that,  just comment the line 75(`var $valid = $('#wizardForm').valid();`), too.

Best, 
Ciprian
