### ISSUE TITLE
Hover Labels broken on JVector Maps.

### ISSUE THREAD

**Issue by knightshade23** [creativetimofficial/ct-paper-dashboard-pro-angular#10]
Compare/Contrast:
http://jvectormap.com/examples/world-gdp/
http://demos.creative-tim.com/light-bootstrap-dashboard-pro/examples/dashboard.html

vs:
http://pd-pro-angular.creative-tim.com/dashboard/stats
http://vuejs.creative-tim.com/paper-dashboard-pro/#/admin/overview

You will notice that the first two have hover-events that display the names (or more complex) as labels.

This theme (and the related Vue.js theme) both have them broken (not displaying).

**Comment by knightshade23** [comment]
It has been a bit...
Any luck with fixing the isue with the Hover Labels for JVector maps?

**Comment by chelaruc** [comment]
Hi, @knightshade23. Sorry for the late response. I've made some tests, but I didn't find a solution for this. I will tell you if I'll find a solution.

**Comment by chelaruc** [comment]
fixed in v1.1.0
