### ISSUE TITLE
Webpack rebuilds continuously

### ISSUE THREAD

**Issue by pgwest** [creativetimofficial/ct-paper-dashboard-pro-angular#13]
I just downloaded the paper dashboard pro angular and ran npm install and then ng serve. Webpack loads initially then immediately rebuilds every few seconds. 

What's causing this and how can I remove this? I haven't changed the code at all.

**Comment by chelaruc** [comment]
Hi, @pgwest. I made some tests and I can't reproduce this and I don't think it's from our product. Best, Ciprian
