### ISSUE TITLE
Bootstrap Modal not accessable

### ISSUE THREAD

**Issue by PrabhakaranV1592** [creativetimofficial/ct-paper-dashboard-pro-angular#14]
Hello

I have purchased pro version, in that bootstrap modal is not accessible when it is opened,
can you provide a quick fix

**Comment by alexandru-paduraru** [comment]
@PrabhakaranV1592 thank you for using our product and sorry for the late response, we had the Easter in the team. Can you please send us a link or any steps to reproduce the bug? Then my colleague Ciprian will help you.

Best,
Alex

**Comment by maciz84** [comment]
@alexandru-paduraru I also have this problem. Here is my code:

`                                                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#topModal">
                                                                <i class="fa fa-user" style="color:white;"></i> Big Fish
                                                            </button>`

`                                                <div class="modal fade" id="topModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                    <div class="modal-dialog modal-lg" role="document">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                                <h4 class="modal-title" id="exampleModalLabel">Top (10) Shareholders</h4>
                                                            </div>
                                                            <div class="modal-body">
                                                                <div>
                                                                    <p>BLAH BLAJH</p>
                                                                </div>
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>`

**Comment by MarcosRibeiroJesus** [comment]
I have the same problem with Modal. When I click on button to open the modal the screen dims and I can't do anything, so I have to reload the page. Any solution my friends? @PrabhakaranV1592 @alexandru-paduraru @maciz84 @chelaruc @marqbeniamin

**Comment by chelaruc** [comment]
@MarcosRibeiroJesus Can you tell me what OS and browser do you use?

**Comment by MarcosRibeiroJesus** [comment]
Hello my friend, my OS is **_Linux Mint 18.2 Sonya_** and Browser is **_Chrome Version 65.0.3325.181 (Official Build) (64-bit)_**. Thank you for the good work and have a nice week.

**Comment by MarcosRibeiroJesus** [comment]
Hello guys, somebody has achieved a solution to this? =(

**Comment by MarcosRibeiroJesus** [comment]
Hello everyone any update? @chelaruc @alexandru-paduraru any progress with this? Thank's!

**Comment by prabhakaran-myApps** [comment]
I found a workaround which helped to achive this..


the Work Around is to add the modal code to the parent layout component and call the modal from any component you want.

**Comment by MarcosRibeiroJesus** [comment]
Hello @PrabhakaranV1592 I tried to reproduces you tip on my code but I didn't make this work... Can you tell me what you did specifically? I tried to create a new component with ngTemplate, put the modal on admin Layout... but nothing works. Thanks in advance.

**Comment by prabhakaran-myApps** [comment]
Can you share me you code snippet. and how your calling the modal??

**Comment by MarcosRibeiroJesus** [comment]
I decided to let this really important thing to the next sprint, so I have to focus in another aproache to finalize the functionality, but in the next week I back and show what I tried for see if you can help me. I tried some different''s forms to do that. I saw it maybe happens because of a change in same component of the bootstrap, in another issue I saw the people talking about the difficulty to using modal on children route's and so on. 
In the next week I'll be back. Thanks for the helping.

**Comment by MarcosRibeiroJesus** [comment]
Put modal inside app.component let me open modal, now the problem is to use some components inside the modal because of the problem of schemas, app.component don't recognize the component i try to load inside modal... I try make this work soon and back here. Cheers.

**Comment by rizaldimaulidia** [comment]
Don't put modal div inside &lt;div class=&quot;main-panel&quot;&gt;. Just put the modal in body tag. for example :
&lt;body&gt;
&lt;div class=&quot;wrapper&quot;&gt;
&lt;div class=&quot;sidebar&quot;&gt;&lt;!-- sidebar --&gt;&lt;/div&gt;
&lt;div class=&quot;main-panel&quot;&gt;&lt;!-- content --&gt;&lt;/div&gt;
&lt;/div&gt;

&lt;!-- Bootstrap modal here --&gt;
&lt;div class=&quot;modal fade&quot; tabindex=&quot;-1&quot; role=&quot;dialog&quot;&gt;
&lt;div class=&quot;modal-dialog&quot; role=&quot;document&quot;&gt;
    &lt;div class=&quot;modal-content&quot;&gt;
      &lt;div class=&quot;modal-header&quot;&gt;
        &lt;button type=&quot;button&quot; class=&quot;close&quot; data-dismiss=&quot;modal&quot; aria-label=&quot;Close&quot;&gt;&lt;span aria-hidden=&quot;true&quot;&gt;&amp;times;&lt;/span&gt;&lt;/button&gt;
        &lt;h4 class=&quot;modal-title&quot;&gt;Modal title&lt;/h4&gt;
      &lt;/div&gt;
      &lt;div class=&quot;modal-body&quot;&gt;
        &lt;p&gt;One fine body&amp;hellip;&lt;/p&gt;
      &lt;/div&gt;
      &lt;div class=&quot;modal-footer&quot;&gt;
        &lt;button type=&quot;button&quot; class=&quot;btn btn-default&quot; data-dismiss=&quot;modal&quot;&gt;Close&lt;/button&gt;
        &lt;button type=&quot;button&quot; class=&quot;btn btn-primary&quot;&gt;Save changes&lt;/button&gt;
      &lt;/div&gt;
    &lt;/div&gt;&lt;!-- /.modal-content --&gt;
  &lt;/div&gt;&lt;!-- /.modal-dialog --&gt;
&lt;/div&gt;
&lt;/body&gt;

this works on free version

**Comment by dexoitindia** [comment]
@alexandru-paduraru  We are facing the same issue please help up need solution ASAP
"Bootstrap model show "  class is not assigned while open the bootstrap model. it's working in the browser1 but same thing is not happening in browser2.  (we are using the lastest version of chrome browser.)

Code:
Browser 1 :

`<div ngcontent-c6="" class="**modal fade show**" id="bootstrapModelIcard" role="dialog" **style="display: block;**">`

Browser 2: 

`<div _ngcontent-c3="" class="**modal fade**" id="bootstrapModelIcard" role="dialog">`


if we use "**modal fade show**" and **style="display: block;** in browser 2 for fix the issue we are faciing another issue which is we are unbaled to close bootstrap model.


Thanks in advance.

**Comment by chelaruc** [comment]
Hi, @dexoitindia. What version of the product do you have? Can you tell me the steps to reproduce the error?

**Comment by dexoitindia** [comment]
Dear Chelaru Ciprian,

We are using below Version,
[image: image.png]

Steps for reproducing issue please see video :

1.Login in Template
2.Open side Menu
3. Click on the notification  menu
4. Try for Open Model
5. Black transparent effect showing instead of open pop up window



Thanks.

**Comment by dexoitindia** [comment]
> Hi, @dexoitindia. What version of the product do you have? Can you tell me the steps to reproduce the error?

Dear Chelaru Ciprian,

We are using below Version,
Paper dashboard pro angular V1.1.0

Steps for reproducing issue (Chrome latest version)please see video :

1.Login in Template
2.Open side Menu
3. Click on the notification  menu
4. Try for Open Model
5. Black transparent effect showing instead of open pop up window

https://drive.google.com/open?id=1k55bkpqL7RN4tB_4q3jnQ4uJl6uHoMiE

Thanks.

**Comment by dexoitindia** [comment]
@alexandru-paduraru  We are waiting for your valuable response. please help us ASAP

**Comment by dexoitindia** [comment]
@alexandru-paduraru We are waiting for your valuable response. please help us ASAP

**Comment by chelaruc** [comment]
@dexoitindia it is working on our live demo. I'll make some test on Windows to see where the error occurs.

**Comment by chelaruc** [comment]
I tested on Mac OS and Windows 10 and all is working good.

**Comment by dexoitindia** [comment]
Thanks, I'll check it out.
