### ISSUE TITLE
Use of moduleID

### ISSUE THREAD

**Issue by Sauravsam85** [creativetimofficial/ct-paper-dashboard-pro-angular#20]
Hi,

I want to understand the usage of moduleID in component.ts files.
What is the purpose of using it?

While building the code using ng build, it fails for component.ts files which have moduleId: module.id.
The following error is received: Cannot find name 'module'.

Any help is appreciated.
Thanks
Saurav

**Comment by chelaruc** [comment]
@Sauravsam85 you can remove it. It was for an older Angular version.
