### ISSUE TITLE
SweetDialog don't load components

### ISSUE THREAD

**Issue by jhonatan2760** [creativetimofficial/ct-paper-dashboard-pro-angular#22]
Hello everyone, i've a problem with sweet dialog, when i need to create 
a modal dialog with a form, i'm not be able to use a Custom Angular Component, directive
or some else that uses @Angular/core.

`
swal({
                title: 'Input something',
                html: '<app-my-custom-component></app-my-custom-component>'
})
`

Regrats.

**Comment by MarcosRibeiroJesus** [comment]
I want to know if it's possible too.

**Comment by chelaruc** [comment]
@jhonatan2760 @MarcosRibeiroJesus check this out: [https://github.com/sweetalert2/ngx-sweetalert2#swalpartialdirective](https://github.com/sweetalert2/ngx-sweetalert2#swalpartialdirective) and tell me if it helps you. Best, Ciprian

**Comment by jhonatan2760** [comment]
Thanks bro!

**Comment by jhonatan2760** [comment]
> I want to know if it's possible too.

Não sei Marcos, até agora nada e você? kkkkk
