### ISSUE TITLE
Problem using 1.1.0 modal dialogs

### ISSUE THREAD

**Issue by Sauravsam85** [creativetimofficial/ct-paper-dashboard-pro-angular#23]
Hi @chelaruc , I bought Paper Dashboard Pro Angular 1.0.1 and have been loving it.
I recently noticed that you updated it to version 1.1.0, and I found that you had added modals as well. What would I need to do in order to incorporate that in my project?
I am using angular 4.4.4 and would prefer keeping it the same. I have updated my package.json to use Bootstrap 4.1.3.

But when I try and open a modal it does not popup, I cannot post an image as it does not update my page, although I see a white stripe on the right side of my page (may be the dialog opened there), but I am not able to view it even after changing the page size and I cannot click or work on the page after that, I have to refresh my page in order for it to work.

Any help will be greatly appreciated.
Thanks.

**Comment by Sauravsam85** [comment]
@alexandru-paduraru @timcreative Can I please get some support here?

**Comment by chelaruc** [comment]
@Sauravsam85 Thank you for using our product and for the kind words. Can you send me an archive for testing to ciprian@creative-tim.com? I can try to fix it on your project. Best, Ciprian

**Comment by Sauravsam85** [comment]
Ciprian, it will not be possible for me to send you my working archive for testing. If you could let me know what were the layout changes and structural changes in your new version, I can try and incorporate that into my old version.
