### ISSUE TITLE
collapsible accordion

### ISSUE THREAD

**Issue by shalvy** [creativetimofficial/ct-paper-dashboard-pro-angular#25]
How do I make to work this way, say Collapsible Group Item #1 is already collapse, when I click the second item to collapse e.g Collapsible Group Item #2 , Collapsible Group Item #1 or any other collapsed items to  un-collapses/closes and only Collapsible Group Item #2 is left collapsed, Help please??

`<div id="accordion">
  <div class="card">
    <div class="card-header">
      <a class="card-link" data-toggle="collapse" href="#collapseOne">
        Collapsible Group Item #1
      </a>
    </div>
    <div id="collapseOne" class="collapse show" data-parent="#accordion">
      <div class="card-body">
        Lorem ipsum..
      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-header">
      <a class="collapsed card-link" data-toggle="collapse" href="#collapseTwo">
        Collapsible Group Item #2
      </a>
    </div>
    <div id="collapseTwo" class="collapse" data-parent="#accordion">
      <div class="card-body">
        Lorem ipsum..
      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-header">
      <a class="collapsed card-link" data-toggle="collapse" href="#collapseThree">
        Collapsible Group Item #3
      </a>
    </div>
    <div id="collapseThree" class="collapse" data-parent="#accordion">
      <div class="card-body">
        Lorem ipsum..
      </div>
    </div>
  </div>

</div>`

**Comment by chelaruc** [comment]
@shalvy you need to change the data-parent="#accordion" to the divs with the class collapse. For example, the first collapsible from Panels page will look like:
```
<div id="accordion" role="tablist" aria-multiselectable="true" class="card-collapse">
            <h4 class="card-title">Collapsible Accordion</h4>
            <div class="card card-plain">
              <div class="card-header" role="tab" id="headingOne">
                <a data-toggle="collapse" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                  Collapsible Group Item #1
                  <i class="nc-icon nc-minimal-down"></i>
                </a>
              </div>
              <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
                <div class="card-body">
                  Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                </div>
              </div>
            </div>
            <div class="card card-plain">
              <div class="card-header" role="tab" id="headingTwo">
                <a class="collapsed" data-toggle="collapse"href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                  Collapsible Group Item #2
                  <i class="nc-icon nc-minimal-down"></i>
                </a>
              </div>
              <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
                <div class="card-body">
                  Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                </div>
              </div>
            </div>
            <div class="card card-plain">
              <div class="card-header" role="tab" id="headingThree">
                <a class="collapsed" data-toggle="collapse" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                  Collapsible Group Item #3
                  <i class="nc-icon nc-minimal-down"></i>
                </a>
              </div>
              <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
                <div class="card-body">
                  Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                </div>
              </div>
            </div>
          </div>
```

All the best,
Ciprian

**Comment by shalvy** [comment]
Hey Ciprian,

Yes thank you, worked exactly as I wanted cheers mate 👍..

thanks,
shalvy

**Comment by shalvy** [comment]
well what I am trying to do exactly, the html is like this
<div id="accordion" role="tablist" aria-multiselectable="true" class=
"card-collapse">
<ul>
<li *ngFor="let o of options">
<div class="card card-plain">
<div class="card-header" role="tab" id="heading2">
<a class="collapsed" data-toggle="collapse" href="#{{ o.name }}"
aria-expanded="false"
aria-current="false">{{ o.name }}<i class="nc-icon nc-minimal-down"></i></a>
</div>
<div id="{{ o.name }}" class="collapse" data-parent="#accordion" role=
"tabpanel"
aria-labelledby="heading2">
<div class="card-body">
<ol>
<li *ngFor="let task of data"> {{ task.name }}</li>
</ol>
</div>
</div>
</div>
</li>
</ul>
</div>

data from the ts be like this;

options = [
{ name: "option1", value: 1 },
{ name: "option2", value: 2 },
{ name: "option2", value: 3 },
{ name: "option2", value: 4 },
{ name: "option2", value: 5 },
{ name: "option3", value: 6 }
]

data = [
{ name: "apple", value: 1 },
{ name: "banana", value: 2 }
]

**Comment by shalvy** [comment]
it worked thanks
