### ISSUE TITLE
Page in white when throw ng serve after to add a new component

### ISSUE THREAD

**Issue by henryespinoza89** [creativetimofficial/ct-paper-dashboard-pro-angular#27]
Hello,

I've a problem with the product when I make changes in the code. When I start the project for first time I don't have problems, but when I return next day and throw ng serve, I have the page in white, nothing in console browser or an error in cmd console.

Just unzipd and run npm install, ng serve then I added a new component in the project and then always throw me a page in white.

Other things is when i run ng serve always show me this:

 The `text-hide()` mixin has been deprecated as of v4.1.0. It will be removed entirely in v5.
         on line 10 of node_modules/bootstrap/scss/mixins/_text-hide.scss, in mixin `text-hide`
         from line 57 of node_modules/bootstrap/scss/utilities/_text.scss
         from line 14 of node_modules/bootstrap/scss/_utilities.scss
         from line 41 of node_modules/bootstrap/scss/bootstrap.scss
         from line 15 of stdin

**Comment by chelaruc** [comment]
@henryespinoza89 can you tell me what error you got?
