### ISSUE TITLE
Login and lock page have unneeded vertical scrollbar

### ISSUE THREAD

**Issue by timdows** [creativetimofficial/ct-paper-dashboard-pro-angular#28]
Login and lock page have unneeded vertical scrollbar
Can be seen on the demo page as well:
https://demos.creative-tim.com/paper-dashboard-pro-angular/pages/login

<img width="680" alt="2019-01-17 13_18_27" src="https://user-images.githubusercontent.com/9577532/51318430-9b83dd80-1a5a-11e9-8aa2-2806e3eac7d7.png">

Register page does not have this issue

**Comment by chelaruc** [comment]
Hi, @timdows. Thank you for using our product and we are sorry for the late response. All you have to do is to go in `src/assets/scss/paper-dashboard/_sidebar-and-main-panel.scss` file and delete the line 8: `height: auto;`. 
Let us know if it works.

All the best,
Ciprian

**Comment by timdows** [comment]
Hi Ciprian,
This works perfect for the login page.

I hoped it would also fix the other pages unneeded scrollbar
E.g. on https://demos.creative-tim.com/paper-dashboard-pro-angular/components/sweet-alert

Let me know how to fix that unneeded scrollbar
Thanks in advance!

**Comment by timdows** [comment]
@chelaruc Any thoughts?

**Comment by chelaruc** [comment]
@timdows sorry for the late response. Go in `src/assets/scss/paper-dashboard/_sidebar-and-main-panel.scss` file and replace the line 456 with:
```
    min-height: calc(100vh - 163px);
```

**Comment by timdows** [comment]
Works like a charm! Thanks
