### ISSUE TITLE
3 dots menu's options do not overlapping the content properly

### ISSUE THREAD

**Issue by mpresinal** [creativetimofficial/ct-paper-dashboard-pro-angular#29]
Hello, I have found an issue when the page is displayed on any small devices. When you click the 3 dots button on the top right, the options displayed is not overlapping the content properly. Instead the page content and the 3 dots menu's options are getting mixed. See the image below

![image](https://user-images.githubusercontent.com/875881/53181925-e3a09d80-35ce-11e9-893f-4b38eda1c7c0.png)

Just setting the same background color as main-panel got, fix the issue.

**Comment by chelaruc** [comment]
fixed in v1.2.0
