### ISSUE TITLE
menu bar disappears when scrolling in mobile mode

### ISSUE THREAD

**Issue by astangadude** [creativetimofficial/ct-paper-dashboard-pro-angular#33]
In mobile mode the top menu bar disappears when scrolling

**Comment by chelaruc** [comment]
@astangadude Thank you for using our product. All you have to do is to add
```
  &.fixed-top{
      position: fixed !important;
    }
```
on line 18 in the `src/assets/scss/paper-dashboard/_navbar.scss` file.
