### ISSUE TITLE
Documentation for Paper Dashboard Pro Angular

### ISSUE THREAD

**Issue by sethura** [creativetimofficial/ct-paper-dashboard-pro-angular#35]
I purchased Paper Dashboard Pro Angular product but when I go to documentation link: https://demos.creative-tim.com/paper-dashboard-pro-angular/documentation/tutorial it does not work .

Please provide the correct access link to documentation for Paper Dashboard Pro Angular product.

Thank you.

**Comment by chelaruc** [comment]
Hi, @sethura. Thank you for using our product. The documentation is here: https://demos.creative-tim.com/paper-dashboard-pro-angular/#/documentation/tutorial
