### ISSUE TITLE
[Bug] Toggle Buttons use inside the form

### ISSUE THREAD

**Issue by sethura** [creativetimofficial/ct-paper-dashboard-pro-angular#36]
### Version
v1.2.0
### Reproduction link
https://dash1.softveer.com/#/forms/validation
### Operating System
Windows 10
### Device
PC
### Browser & Version
Chrome 74
### Steps to reproduce
I cannot figure out how to use your toggle buttons inside of my HTML form. Could you please provide an example with HTML form that uses your Toggle Buttons, so the user will just use <bSwitch> control to say On or Off  to the question "Subscribe to newsletter"posted in the HTML form ?
### What is expected?
A working form with Toggle Button working. 
### What is actually happening?
Toggle Buttons is visible on the form but it does not activate the Yes or No input inside the HTML form field.

---

**Comment by sethura** [comment]
I paid for 1 year of support for Paper Dashboard Pro Angular product and these guys from Creative Tim don't even notice the requests. Also I am filing a request for help on the github site like everybody else who did not pay for the support... Where is the priority communication channel for customers that paid for the support ? This is ridiculous !

**Comment by chelaruc** [comment]
Hi, @sethura. Thank you for using our product and sorry for the late response. To make it work, you need to move the switch code from the label. Here is the example for your case:
```
<div class="form-check pull-left">
       <bswitch></bswitch>
       <label class="form-check-label"> Subscribe to newsletter </label>
</div>
```

All the best,
Ciprian
