### ISSUE TITLE
Login responsive missing

### ISSUE THREAD

**Issue by nikiller291189** [creativetimofficial/ct-paper-dashboard-pro-angular#37]
<div class="wrapper-full-page">
    <div class="full-page section-image" filter-color="black" data-image="">
        
        <div class="content">

            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="col-lg-8 col-md-8 col-sm-12 text-white text-center pull-left">
                        <h3 class="info-title"> Welcome To Patient Portal</h3>
                        <h6> Access Your Medical Records And Stay Connected.</h6>
                        <p>
                            The Patient Portal allows you to securely access your medical records and stay connected with your medical provider office. We are dedicated to providing 24x7 convenient access to your medical information.
                        </p>
                        <div class="row">
                            <div class="col-lg-3 col-md-3 col-sm-3">
                                <div class="card-stats">
                                    <div class="card-body ">

                                        <div class="icon-big text-center">
                                            <i class="nc-icon nc-credit-card text-primary"></i>
                                        </div>

                                    </div>
                                    <div>
                                        e Statements & Online payments
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-2">
                                <div class="card-stats">
                                    <div class="card-body ">

                                        <div class="icon-big text-center">
                                            <i class="nc-icon nc-calendar-60 text-primary"></i>
                                        </div>

                                    </div>
                                    <div>
                                        View and request appointments
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-2">
                                <div class="card-stats">
                                    <div class="card-body ">

                                        <div class="icon-big text-center">
                                            <i class="nc-icon nc-ruler-pencil text-primary"></i>
                                        </div>

                                    </div>
                                    <div>
                                        Request Prescription Refills
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-3">
                                <div class="card-stats">
                                    <div class="card-body ">

                                        <div class="icon-big text-center">
                                            <i class="nc-icon nc-ambulance text-primary"></i>
                                        </div>

                                    </div>
                                    <div>
                                        Immunization and Lab Results
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-2">
                                <div class="card-stats">
                                    <div class="card-body ">

                                        <div class="icon-big text-center">
                                            <i class="nc-icon nc-email-85 text-primary"></i>
                                        </div>

                                    </div>
                                    <div>
                                        <div class="row">
                                            Securely Message Office Staff
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 ml-auto mb-auto">
                        <form class="form" method="" action="">
                            <div class="card card-login">
                                <div class="ml-auto mr-auto">
                                    <img alt="image" src="../../../assets/img/login-logo.png" />
                                </div>
                                <div class="card-header ">
                                    <h6 class="header text-center">LOGIN TO YOUR ACCOUNT</h6>
                                </div>
                                <div class="card-body ">
                                    <div class="input-group" [ngClass]="{'input-group-focus':focus===true}">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <i class="nc-icon nc-single-02"></i>
                                            </span>
                                        </div>
                                        <input type="text" class="form-control" placeholder="User Name..." (focus)="focus=true" (blur)="focus=false">
                                    </div>
                                    <div class="input-group" [ngClass]="{'input-group-focus':focus1===true}">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <i class="nc-icon nc-key-25"></i>
                                            </span>
                                        </div>
                                        <input type="password" placeholder="Password" class="form-control" (focus)="focus1=true" (blur)="focus1=false">
                                    </div>
                                    <br />
                                    <div class="form-group">
                                        <a routerLinkActive="active">
                                            Forgot Password
                                        </a>
                                    </div>
                                </div>
                                <div class="card-footer ">
                                    <a href="javascript:void(0)"  class="btn btn-warning btn-round btn-block mb-3">Log In</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>

**Comment by chelaruc** [comment]
Closed because you haven't used ISSUE_TEMPLATE
