### ISSUE TITLE
[Bug] Tooltips not working

### ISSUE THREAD

**Issue by zdmano** [creativetimofficial/ct-paper-dashboard-pro-angular#39]
### Version
1.3.0
### Reproduction link
https://demos.creative-tim.com/paper-dashboard-pro-angular/#/dashboard
### Operating System
MAC OS
### Device
Macbook
### Browser & Version
Chrome 81
### Steps to reproduce
Browse to : 
https://demos.creative-tim.com/paper-dashboard-pro-angular/#/dashboard -> hover over the tasks card buttons at the end . 

The HTML version seems to work ok.
### What is expected?
Tooltips should show
### What is actually happening?
Tooltips aren't showing

---

**Comment by zdmano** [comment]
It seems there is no place where tooltips are initialized . 

A search for 
`    $('[rel="tooltip"]').tooltip();`
brings up nothing

**Comment by rarestoma** [comment]
Hi @zdmano,

Thank you for working with our products and for pointing us this issue.

Please add the following code in `dashboard.component.ts` in interior of `export class DashboardComponent implements OnInit ` function:

ngAfterViewInit(){
      // Init Tooltips
      $('[rel="tooltip"]').tooltip();
  }


Please let me know if it works.

Thank you,
Rares

**Comment by zdmano** [comment]
It worked but in the end I opted for using ng-bootstrap across the app. 

Nonetheless I think the fix you mentioned should be included in an update.

Thanks
