### ISSUE TITLE
Datetime picker doesn't fire ngModelChange event or does not update model value.

### ISSUE THREAD

**Issue by rayvaz** [creativetimofficial/ct-paper-dashboard-pro-angular#4]
Hi, 
when i try to use date picker, its changing input values visually but the model doesnt change.

<input type="text" class="form-control datepicker" placeholder="Today"(ngModelChange)="updateMyDate($event)" [ngModel]="today" name="today">

**Comment by chelaruc** [comment]
@rayvaz Sorry for the late response! Can you try this module for datepicker? https://www.npmjs.com/package/eonasdan-bootstrap-datetimepicker
We will change the current datetimepicker from current version with this module because we have a lot of issues with it too.

Best,
Ciprian
