### ISSUE TITLE
[Bug] Angular 13 - UI header misaligned

### ISSUE THREAD

**Issue by mrseanr** [creativetimofficial/ct-paper-dashboard-pro-angular#42]
### Version
1.5.0
### Reproduction link
https://github.com/creativetimofficial/ct-paper-dashboard-pro-angular
### Operating System
Mac OS Monterey
### Device
2021 Macbook Pro (M1 Pro Chipset)
### Browser & Version
Chrome v. 101.0.4951.41
### Steps to reproduce
1. download zip
2. extract to folder
3. open vs code
4. npm install
5. ng s
6. open chrome
7. browse to "http://localhost:4200"
### What is expected?
All UI elements aligned properly
### What is actually happening?
On the M1-Pro Macbook Pro the UI elements are misaligned

---
### Additional comments
This issue appears to only affect the M1 (or M1-pro) variants.
If I build this on my 2016 Macbook Pro (Intel chipset) - with the same chrome version - the bug doesn't appear.
Additionally - this doesn't appear to happen on Safari (v.15.4) on the same machine

**Comment by mrseanr** [comment]
![Screen Shot 2022-04-29 at 9 01 33 AM](https://user-images.githubusercontent.com/17507370/165961184-46baf365-989b-476e-bb0a-192a9dc0c052.png)
Screenshot from Chrome

**Comment by mrseanr** [comment]
<img width="1436" alt="Screen Shot 2022-04-29 at 9 10 53 AM" src="https://user-images.githubusercontent.com/17507370/165961312-34fb0bf8-23e2-48bc-a31d-6fc1a443b3cc.png">
Screenshot from Safari (v.15.4)

**Comment by mrseanr** [comment]
It appears to be a CSS issue. the "main-content" styling
![Screen Shot 2022-04-29 at 3 24 06 PM](https://user-images.githubusercontent.com/17507370/166064292-538b4f80-32b2-48c8-8e07-3df585bd782c.png)
.

**Comment by rarestoma** [comment]
Hi @mrseanr,

Thank you for working with our products.
 
To fix this issue please go to `src/assets/scss/paper-dashboard/_navbar.scss` and on line 74, where &.navbar-absolute style is written, add` top: 0;`:
 
```
    &.navbar-absolute{
        position: absolute;
        top: 0;
        width: 100%;
        padding-top: 10px;
        z-index: 1029;
    }
```
 
Please let me know if it works.
 
Best regards,
Rares

**Comment by mrseanr** [comment]
Thank you @rarestoma - That worked.
