### ISSUE TITLE
The customizable select does not work with angular for

### ISSUE THREAD

**Issue by criti18** [creativetimofficial/ct-paper-dashboard-pro-angular#7]
The single select and the multiple select don't work with the angular cycles. The data just doesn't appear in the options, I have tried with local arrays and I get the same result. It's important that this works with the NGFor because I receive information by the webservices.

**Comment by chelaruc** [comment]
Hi, @criti18! Thank you for using our product! Can you init bootstrap select picker in AfterViewInit? Like:
````
ngAfterViewInit(){
        //  Init Bootstrap Select Picker
        if($(".selectpicker").length != 0){
            $(".selectpicker").selectpicker({
                iconBase: "ti",
                tickIcon: "ti-check"
            });
        }

    }
````
And don't forget to import AfterViewInit.
Tell me if it worked.

All the best,
Ciprian

**Comment by criti18** [comment]
I tried, but I have the same result the select disappears with any ngIf, any ideas?

**Comment by chelaruc** [comment]
@criti18 
I've made some tests and I'm thinking this is a solution:
For .ts:
<img width="348" alt="screen shot 2017-12-13 at 10 51 35" src="https://user-images.githubusercontent.com/22840626/33929882-b3eac3ea-dff3-11e7-8a9c-27151da855cc.png">
For .html:
<img width="662" alt="screen shot 2017-12-13 at 10 53 26" src="https://user-images.githubusercontent.com/22840626/33929933-e0e59d16-dff3-11e7-86a4-9998ee4fce56.png">

And delete:
````
//  Init Bootstrap Select Picker
        if($(".selectpicker").length != 0){
            $(".selectpicker").selectpicker({
                iconBase: "ti",
                tickIcon: "ti-check"
            });
        }
````
Tell me if it worked!

Best,
Ciprian

**Comment by Sauravsam85** [comment]
Did this ever work for web services?

**Comment by chelaruc** [comment]
@Sauravsam85 we are not working with web services, that's why I can't tell you for sure if it's working. Best, Ciprian
